version: '3'
services:
  cat:
    build: .
    environment:
      MYSQL_DATABASE: cat
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "8080:8080"
    volumes:
      - ".:/go/src/cat"
    command: go run db/migrate.go
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: cat
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
