version: '3'
services:
  cat:
    build: .
    environment:
      MYSQL_DATABASE: cat
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    tty: true
  db:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: cat
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
